-- ============================================================
-- Seed:        031_seed_downtime_reason_codes.sql
-- Author:      Blue Ridge Automation
-- Date:        2026-07-31
-- Description: Load the 353 FRS Appendix downtime reason codes into
--              Oee.DowntimeReasonCode. These were previously loaded into dev
--              only by the MANUAL Oee.DowntimeReasonCode_BulkLoadFromSeed proc
--              (not in the reset path), so any dev reset dropped them and the
--              Downtime Manager dropdown fell back to just the migration-seeded
--              LUNCH/BREAK1/BREAK2 (0026). This seed wires them into the reset
--              path, mirroring 030_seed_defect_codes.sql. Source:
--              reference/seed_data/downtime_reason_codes.csv.
--
--              Code = DeptCode + '-' + zero-padded ReasonId (matches
--              DowntimeReasonCode_BulkLoadFromSeed exactly, e.g. DC-0003), so
--              a later manual bulk-load re-run stays idempotent.
--              DowntimeReasonTypeId = CSV TypeId when it resolves to a seeded
--              Oee.DowntimeReasonType row, else NULL (301 rows carry no type in
--              the CSV -- engineering backfills, Phase 8 Q-B). DowntimeSource /
--              StandardDurationMinutes NULL on load.
--
--              Department -> OperationCategory mapping (FAT #3, mirrors 030's
--              defect-code scoping): DC -> DieCast, MS -> MachiningAssembly,
--              TS -> Trim. Codes are scoped by PROCESS, so every area in a category
--              (DC1-4, MA1-2, TRIM1-2) sees them. CreatedByUserId = SYS bootstrap user.
--              Idempotent on UQ code (insert-where-not-exists). ASCII-only.
-- ============================================================

SET NOCOUNT ON;

DECLARE @DieCast BIGINT = (SELECT Id FROM Parts.OperationCategory WHERE Code = N'DieCast');
DECLARE @MachAsm BIGINT = (SELECT Id FROM Parts.OperationCategory WHERE Code = N'MachiningAssembly');
DECLARE @Trim    BIGINT = (SELECT Id FROM Parts.OperationCategory WHERE Code = N'Trim');
DECLARE @Usr BIGINT = COALESCE((SELECT Id FROM Location.AppUser WHERE Initials = N'SYS'),
                               (SELECT MIN(Id) FROM Location.AppUser));

IF @DieCast IS NULL OR @MachAsm IS NULL OR @Trim IS NULL OR @Usr IS NULL
BEGIN
    PRINT 'Seed 031 SKIPPED: missing OperationCategory (DieCast/MachiningAssembly/Trim) or AppUser -- run after migrations + AppUser seed.';
    RETURN;
END

DECLARE @Codes TABLE (Code NVARCHAR(20), Description NVARCHAR(500), OperationCategoryId BIGINT, DowntimeReasonTypeId INT, IsExcused BIT);

INSERT INTO @Codes (Code, Description, OperationCategoryId, DowntimeReasonTypeId, IsExcused) VALUES
(N'DC-0001', N'Scheduled Downtime', @DieCast, 6, 0),
(N'DC-0002', N'Mold Change', @DieCast, 5, 0),
(N'DC-0003', N'Machine Repair', @DieCast, 1, 1),
(N'DC-0004', N'Mold Repair', @DieCast, 3, 1),
(N'DC-0005', N'Bad Repair', @DieCast, 3, 1),
(N'DC-0006', N'Cam Repair', @DieCast, 3, 1),
(N'DC-0007', N'Sprayer Adjustment', @DieCast, 1, 0),
(N'DC-0008', N'Sprayer Repair', @DieCast, 1, 0),
(N'DC-0009', N'Trim Press Adjustment', @DieCast, 1, 1),
(N'DC-0010', N'Trim Press Repair/Adjustment', @DieCast, 1, 0),
(N'DC-0011', N'Trim Die Repair', @DieCast, 3, 0),
(N'DC-0012', N'Furnace Trouble', @DieCast, 1, 0),
(N'DC-0013', N'AK Porter', @DieCast, 1, 0),
(N'DC-0014', N'Sleeve and Tip', @DieCast, 1, 1),
(N'DC-0015', N'Die Lube System', @DieCast, 1, 0),
(N'DC-0016', N'Machine Start-Up/Preheat', @DieCast, 2, 0),
(N'DC-0017', N'Sample Test Work', @DieCast, 2, 1),
(N'DC-0018', N'Insert Machine Trouble', @DieCast, 1, 1),
(N'DC-0019', N'Flash Removal (@ Machine)', @DieCast, 3, 0),
(N'DC-0020', N'Machine Adjustment', @DieCast, 1, 1),
(N'DC-0021', N'Extractor Repair/Adjustment', @DieCast, 1, 0),
(N'DC-0022', N'Extractor Adjustment', @DieCast, 1, 1),
(N'DC-0023', N'Auto Ladle Repair', @DieCast, 1, 0),
(N'DC-0024', N'No Rocker Arm Inserts', @DieCast, 2, 1),
(N'DC-0025', N'Broken Crane', @DieCast, 1, 0),
(N'DC-0026', N'No Operator', @DieCast, 2, 1),
(N'DC-0027', N'Computer Problems', @DieCast, 1, 1),
(N'DC-0028', N'Conveyor Problems', @DieCast, 1, 0),
(N'DC-0029', N'Thermo Cast Problems', @DieCast, 1, 1),
(N'DC-0030', N'N/G Production Time', @DieCast, 2, 1),
(N'DC-0031', N'No Baskets', @DieCast, 2, 1),
(N'DC-0032', N'Waiting on Q.C. Approval', @DieCast, 4, 1),
(N'DC-0033', N'Sorting or Repairing Parts', @DieCast, 4, 1),
(N'DC-0034', N'Cooling Tower/Water Pressure', @DieCast, 2, 1),
(N'DC-0035', N'Power Outage', @DieCast, 2, 1),
(N'DC-0036', N'Emergency Evacuation/Shutdown', @DieCast, 2, 1),
(N'DC-0037', N'Solder Removal (@ Machine)', @DieCast, 3, 0),
(N'DC-0038', N'Hydraulic Core Trouble', @DieCast, 3, 1),
(N'DC-0039', N'Low Air Pressure', @DieCast, 1, 0),
(N'DC-0040', N'Gripper Trouble', @DieCast, 1, 1),
(N'DC-0041', N'Tool Measure', @DieCast, 1, 1),
(N'DC-0042', N'Robot/Gripper', @DieCast, 1, 0),
(N'DC-0043', N'Tool Change', @DieCast, 1, 1),
(N'DC-0044', N'Part Detect Sensors', @DieCast, 1, 0),
(N'DC-0045', N'Tool Sensor''s Not Reading', @DieCast, 1, 1),
(N'DC-0046', N'Die Table Changeover', @DieCast, 1, 1),
(N'DC-0047', N'Waiting on Maintenance', @DieCast, 2, 1),
(N'DC-0048', N'Tool Life Count Up', @DieCast, 1, 1),
(N'DC-0049', N'Stuck Part', @DieCast, 1, 0),
(N'DC-0050', N'Waiting for Parts', @DieCast, 2, 1),
(N'DC-0051', N'Thermal Pictures', @DieCast, 1, 1),
(N'DC-0052', N'Waiting for Tech/Team Leader', @DieCast, NULL, 1),
(N'DC-0053', N'Broken Drill', @DieCast, NULL, 1),
(N'DC-0054', N'Engraver', @DieCast, NULL, 0),
(N'DC-0055', N'No Parts', @DieCast, NULL, 1),
(N'DC-0056', N'COP', @DieCast, NULL, 1),
(N'DC-0057', N'Preventive Maintenance', @DieCast, NULL, 1),
(N'DC-0058', N'Training New Associate', @DieCast, NULL, 1),
(N'DC-0059', N'Waiting for Crane', @DieCast, NULL, 0),
(N'DC-0064', N'Preventive Maintenance', @DieCast, NULL, 0),
(N'DC-0066', N'Quench Tank', @DieCast, NULL, 0),
(N'DC-0067', N'Quench Tank Fixtures', @DieCast, NULL, 1),
(N'DC-0068', N'Machine Overheating', @DieCast, NULL, 1),
(N'DC-0069', N'D/C Machine Hyd.', @DieCast, NULL, 0),
(N'DC-0070', N'D/C Machine Elec.', @DieCast, NULL, 0),
(N'DC-0071', N'D/C Machine Mech.', @DieCast, NULL, 0),
(N'DC-0072', N'Mold Repair - Broken/Bent Pin', @DieCast, NULL, 0),
(N'DC-0073', N'Mold Repair-Bent Pin', @DieCast, NULL, 1),
(N'DC-0074', N'Mold Repair-Broken Die', @DieCast, NULL, 1),
(N'DC-0075', N'Mold Repair-Water Leak', @DieCast, NULL, 0),
(N'DC-0076', N'Mold Repair - Dimensional/Broken Die', @DieCast, NULL, 0),
(N'DC-0077', N'Mold Repair-Flashing', @DieCast, NULL, 0),
(N'DC-0078', N'Tip/Coupling', @DieCast, NULL, 0),
(N'DC-0079', N'Sleeve Change', @DieCast, NULL, 0),
(N'DC-0080', N'Tip Lube Line Repair', @DieCast, NULL, 0),
(N'DC-0081', N'Change Tip Coupling', @DieCast, NULL, 1),
(N'DC-0082', N'Sleeve Adjustments', @DieCast, NULL, 0),
(N'DC-0083', N'Shot Bead Unit', @DieCast, NULL, 0),
(N'DC-0084', N'Change Date Pin', @DieCast, NULL, 0),
(N'DC-0085', N'Quality Check', @DieCast, NULL, 0),
(N'MS-0087', N'OP0-1 Down', @MachAsm, NULL, 0),
(N'MS-0088', N'OP0-2 Down', @MachAsm, NULL, 0),
(N'DC-0089', N'No Operator', @DieCast, NULL, 0),
(N'DC-0090', N'Ladel Sensor', @DieCast, NULL, 0),
(N'DC-0091', N'ELB Cam Cords', @DieCast, NULL, 0),
(N'DC-0092', N'COP', @DieCast, NULL, 0),
(N'DC-0093', N'Waiting on MRO', @DieCast, NULL, 0),
(N'DC-0094', N'Vacuum System', @DieCast, 1, 0),
(N'TS-0201', N'Scheduled Down /////////////////////////////', @Trim, NULL, 0),
(N'TS-0202', N'Power Outage', @Trim, NULL, 0),
(N'TS-0203', N'Emergency Evacuation', @Trim, NULL, 0),
(N'TS-0204', N'Low Air Pressure', @Trim, NULL, 0),
(N'TS-0205', N'No Operator', @Trim, NULL, 0),
(N'TS-0206', N'Gripper Trouble', @Trim, NULL, 0),
(N'TS-0207', N'Tool Measure', @Trim, NULL, 0),
(N'TS-0208', N'Robot Position Trouble', @Trim, NULL, 0),
(N'TS-0209', N'Tool Change', @Trim, NULL, 0),
(N'TS-0210', N'Part Detect Sensors', @Trim, NULL, 0),
(N'TS-0211', N'Tool Sensors not Reading', @Trim, NULL, 0),
(N'TS-0212', N'Conveyor Trouble', @Trim, NULL, 0),
(N'TS-0213', N'Die Table Change-Over', @Trim, NULL, 0),
(N'TS-0214', N'No Parts', @Trim, NULL, 0),
(N'TS-0215', N'Running Test Parts', @Trim, NULL, 0),
(N'TS-0216', N'Waiting on Q.C. Approval', @Trim, NULL, 0),
(N'TS-0217', N'Waiting on Maintenance', @Trim, NULL, 0),
(N'TS-0218', N'Tool Life Count Up', @Trim, NULL, 0),
(N'TS-0219', N'Stuck Part', @Trim, NULL, 0),
(N'TS-0220', N'Table Sensor Not Reading', @Trim, NULL, 0),
(N'TS-0221', N'Safety Meeting', @Trim, NULL, 0),
(N'TS-0222', N'Grinder Trouble', @Trim, NULL, 0),
(N'TS-0226', N'Sort Parts', @Trim, NULL, 0),
(N'TS-0229', N'C.O.P.', @Trim, NULL, 1),
(N'TS-0230', N'No Dunnage/Baskets', @Trim, NULL, 1),
(N'MS-0401', N'Air Leak on Machine/////////////////////////////////', @MachAsm, NULL, 1),
(N'MS-0402', N'Assembly Machine Problems', @MachAsm, NULL, 0),
(N'MS-0403', N'Awaiting Leader to Reset Red Light', @MachAsm, NULL, 1),
(N'MS-0404', N'Broken Tool Change', @MachAsm, NULL, 0),
(N'MS-0405', N'C.O.P.', @MachAsm, NULL, 1),
(N'MS-0406', N'Cavity Change/Check', @MachAsm, NULL, 1),
(N'MS-0407', N'Change RA Wheels', @MachAsm, NULL, 1),
(N'MS-0408', N'CMM Confirmation of Changeover', @MachAsm, NULL, 1),
(N'MS-0409', N'CMM Confirmation of Change Point', @MachAsm, NULL, 1),
(N'MS-0410', N'Conveyor Problems', @MachAsm, NULL, 1),
(N'MS-0411', N'Coolant Problems', @MachAsm, NULL, 1),
(N'MS-0412', N'Crash', @MachAsm, NULL, 1),
(N'MS-0413', N'Cycle Stop', @MachAsm, NULL, 0),
(N'MS-0414', N'Dimension Problems', @MachAsm, NULL, 1),
(N'MS-0415', N'Door Problems', @MachAsm, NULL, 0),
(N'MS-0416', N'Dotting Parts', @MachAsm, NULL, 1),
(N'MS-0417', N'Dowel Pin Problems', @MachAsm, NULL, 1),
(N'MS-0418', N'Drills (Fire, Tornado, etc.)', @MachAsm, NULL, 0),
(N'MS-0419', N'Emergency Evacuation/Shutdown', @MachAsm, NULL, 0),
(N'MS-0420', N'Excessive Flash Removal', @MachAsm, NULL, 1),
(N'MS-0421', N'Engineer Working on Machine', @MachAsm, NULL, 0),
(N'MS-0422', N'Hole Size No Good Problem', @MachAsm, NULL, 1),
(N'MS-0423', N'How Long MSM to Repair Machine', @MachAsm, NULL, 0),
(N'MS-0424', N'How Long MSM to Respond', @MachAsm, NULL, 1),
(N'MS-0425', N'Hydraulic Problems', @MachAsm, NULL, 1),
(N'MS-0426', N'Interviews', @MachAsm, NULL, 1),
(N'MS-0427', N'Jig Problems', @MachAsm, NULL, 1),
(N'MS-0428', N'Leak Tester Problems', @MachAsm, NULL, 0),
(N'MS-0429', N'Light Curtain Problems', @MachAsm, NULL, 1),
(N'MS-0430', N'Machine Adjustments', @MachAsm, NULL, 0),
(N'MS-0431', N'Machine Leaking (mopping)', @MachAsm, NULL, 1),
(N'MS-0432', N'MSM Prevenative Maintenance on Machine', @MachAsm, NULL, 1),
(N'MS-0433', N'Machine Trials (New Die Parts, Test Tools, etc)', @MachAsm, NULL, 1),
(N'MS-0434', N'Meetings', @MachAsm, NULL, 1),
(N'MS-0435', N'Pre-shift meetings', @MachAsm, NULL, 1),
(N'MS-0436', N'Misset Problems', @MachAsm, NULL, 1),
(N'MS-0437', N'Changeover', @MachAsm, NULL, 1),
(N'MS-0438', N'Motor Overload/Overheating', @MachAsm, NULL, 1),
(N'MS-0439', N'No Diecast Parts', @MachAsm, NULL, 1),
(N'MS-0440', N'No Operator due to Absence', @MachAsm, NULL, 1),
(N'MS-0441', N'No Operator due to Repacking', @MachAsm, NULL, 1),
(N'MS-0442', N'No Operator due to Repairing Parts', @MachAsm, NULL, 1),
(N'MS-0443', N'No Operator due to Running Other Process', @MachAsm, NULL, 1),
(N'MS-0444', N'No Operator due to Sorting In-House', @MachAsm, NULL, 1),
(N'MS-0445', N'No Operator due to Sorting at Customer', @MachAsm, NULL, 1),
(N'MS-0446', N'No Operator due to Relieving for Breaks/Lunch', @MachAsm, NULL, 1),
(N'MS-0447', N'Low or No Air Pressure', @MachAsm, NULL, 1),
(N'MS-0448', N'No Parts to Assemble', @MachAsm, NULL, 1),
(N'MS-0449', N'No Parts to Inspect', @MachAsm, NULL, 1),
(N'MS-0450', N'No Parts to Lap', @MachAsm, NULL, 1),
(N'MS-0451', N'No Supply Parts', @MachAsm, NULL, 0),
(N'MS-0452', N'No Trim Shop Parts', @MachAsm, NULL, 1),
(N'MS-0453', N'Other', @MachAsm, NULL, 1),
(N'MS-0454', N'Overfilling Machine (mopping)', @MachAsm, NULL, 1),
(N'MS-0455', N'Performing Machine Condition Checks', @MachAsm, NULL, 1),
(N'MS-0456', N'Pin Pressure Problem', @MachAsm, NULL, 1),
(N'MS-0457', N'Power Outage/Surges', @MachAsm, NULL, 0),
(N'MS-0458', N'Probe Problems', @MachAsm, NULL, 1),
(N'MS-0459', N'Quality Problems (misc.)', @MachAsm, NULL, 0),
(N'MS-0460', N'Red Lights for Machining (misc.)', @MachAsm, NULL, 0),
(N'MS-0461', N'Red Lights for Assembly (misc.)', @MachAsm, NULL, 0),
(N'MS-0462', N'Red Lights for Inspection (misc.)', @MachAsm, NULL, 0),
(N'MS-0463', N'Restocking Area of Supplies', @MachAsm, NULL, 1),
(N'MS-0464', N'Safety Problems', @MachAsm, NULL, 1),
(N'MS-0465', N'Schedule Zero Production', @MachAsm, NULL, 1),
(N'MS-0466', N'Seal Problems', @MachAsm, NULL, 1),
(N'MS-0467', N'Sensor Problems', @MachAsm, NULL, 1),
(N'MS-0468', N'Servo Motor/Cable Problems', @MachAsm, NULL, 1),
(N'MS-0469', N'Table Full (Stop Production)', @MachAsm, NULL, 1),
(N'MS-0470', N'Tool Limit (count up)', @MachAsm, NULL, 0),
(N'MS-0471', N'Training', @MachAsm, NULL, 1),
(N'MS-0472', N'Training (Safety)', @MachAsm, NULL, 1),
(N'MS-0473', N'Unknown', @MachAsm, NULL, 1),
(N'MS-0474', N'Waiting on Q.C. Approval', @MachAsm, NULL, 1),
(N'MS-0475', N'Warm Up Machines', @MachAsm, NULL, 1),
(N'MS-0476', N'Washer Failure on Leak Tester', @MachAsm, NULL, 1),
(N'MS-0477', N'Washer (Machine) Problems (down)', @MachAsm, NULL, 0),
(N'MS-0478', N'Worn Tool Change', @MachAsm, NULL, 0),
(N'MS-0479', N'Measuring Parts (C/D, Surfometer, gaging, etc.)', @MachAsm, NULL, 1),
(N'MS-0480', N'ATC Problems', @MachAsm, NULL, 1),
(N'MS-0481', N'Clamp Problems', @MachAsm, NULL, 1),
(N'MS-0482', N'No Dunnage/Baskets', @MachAsm, NULL, 1),
(N'MS-0483', N'Loader Error', @MachAsm, NULL, 1),
(N'MS-0484', N'No PLC Thermo Covers', @MachAsm, NULL, 1),
(N'MS-0485', N'Belt/Timing Problems', @MachAsm, NULL, 1),
(N'MS-0486', N'Spindle Problems', @MachAsm, NULL, 1),
(N'MS-0487', N'Oil Level Low', @MachAsm, NULL, 1),
(N'MS-0488', N'Machine Would Not Start', @MachAsm, NULL, 1),
(N'MS-0489', N'Empty Chip Bins', @MachAsm, NULL, 1),
(N'MS-0490', N'No Water Pressure', @MachAsm, NULL, 1),
(N'MS-0491', N'Plant-Wide Meeting', @MachAsm, NULL, 1),
(N'MS-0492', N'Shutdown High Inventory Level', @MachAsm, NULL, 1),
(N'MS-0493', N'No Operator due to Emptying Recyle Bins', @MachAsm, NULL, 1),
(N'MS-0494', N'Inventory Schedule Down', @MachAsm, NULL, 1),
(N'MS-0495', N'No Operator due to Training New Operator', @MachAsm, NULL, 1),
(N'MS-0496', N'No Operator due to Performing Preventive Maintenan', @MachAsm, NULL, 1),
(N'MS-0497', N'Hearing Test', @MachAsm, NULL, 1),
(N'MS-0498', N'Tool Fell Out', @MachAsm, NULL, 1),
(N'MS-0499', N'CMM Parts', @MachAsm, NULL, 1),
(N'MS-0500', N'Packing Parts', @MachAsm, NULL, 1),
(N'MS-0501', N'No Parts to Machine', @MachAsm, NULL, 1),
(N'MS-0502', N'Check Machine', @MachAsm, NULL, 1),
(N'MS-0503', N'Inspecting', @MachAsm, NULL, 1),
(N'MS-0504', N'Problems with Memory', @MachAsm, NULL, 1),
(N'MS-0508', N'Process Change', @MachAsm, NULL, 1),
(N'MS-0511', N'Inventory', @MachAsm, NULL, 1),
(N'MS-0513', N'Torque Tool Change', @MachAsm, NULL, 1),
(N'MS-0514', N'Sort DC/TS Defects', @MachAsm, NULL, 1),
(N'MS-0515', N'Dowel Pin Feeder', @MachAsm, NULL, 1),
(N'MS-0516', N'OP40 Down', @MachAsm, NULL, 1),
(N'MS-0517', N'Purging Line', @MachAsm, NULL, 1),
(N'MS-0518', N'No parts from previous process', @MachAsm, NULL, 0),
(N'MS-0519', N'Dowel pin feeder down', @MachAsm, NULL, 1),
(N'MS-0520', N'Precautionary Shutdown', @MachAsm, NULL, 1),
(N'MS-0521', N'No User due to Re-Inspection', @MachAsm, NULL, 1),
(N'MS-0522', N'Bolt stuck in chute', @MachAsm, NULL, 1),
(N'MS-0523', N'Waiting on torque gun', @MachAsm, NULL, 1),
(N'MS-0524', N'Spring change', @MachAsm, NULL, 1),
(N'MS-0525', N'No Oper. For running overflow', @MachAsm, NULL, 1),
(N'MS-0527', N'Cleaning/Filling Washer', @MachAsm, NULL, 1),
(N'MS-0528', N'(M02)Face Height Ajustment', @MachAsm, NULL, 1),
(N'MS-0529', N'(M03)Part Height Ajustment', @MachAsm, NULL, 1),
(N'MS-0530', N'(M04)Dow Pin Pitch Ajustment', @MachAsm, NULL, 1),
(N'MS-0531', N'(M11)Scheduled Repair Downtime', @MachAsm, NULL, 1),
(N'MS-0532', N'(M13)Machine Testing Downtime', @MachAsm, NULL, 1),
(N'MS-0533', N'(M15)Repair Downtime by Leader', @MachAsm, NULL, 1),
(N'MS-0534', N'Washing Parts', @MachAsm, NULL, 1),
(N'MS-0535', N'(M01)Cycle Stop', @MachAsm, NULL, 1),
(N'MS-0536', N'(M05)Tool Change & Quality', @MachAsm, NULL, 1),
(N'MS-0537', N'(M06)Broken Tool change & Quality Confirmation', @MachAsm, NULL, 1),
(N'MS-0538', N'(M07)Oper. Moved to other Process', @MachAsm, NULL, 1),
(N'MS-0539', N'(M08)Out of Parts from D/C', @MachAsm, NULL, 1),
(N'MS-0540', N'(M09)Changing Line Over/Purging Line', @MachAsm, NULL, 1),
(N'MS-0541', N'(M10)Unscheduled Machine Repair By Maint.', @MachAsm, NULL, 1),
(N'MS-0542', N'(M12)Machine Down For PM', @MachAsm, NULL, 1),
(N'MS-0543', N'(M14)Machine Alarm', @MachAsm, NULL, 1),
(N'MS-0544', N'(M16)No Oper Due To Absence', @MachAsm, NULL, 1),
(N'MS-0545', N'(M17)Meeting', @MachAsm, NULL, 1),
(N'MS-0546', N'(M18)Maching Shut Down Due To WIP', @MachAsm, NULL, 1),
(N'MS-0547', N'(M19)Other', @MachAsm, NULL, 1),
(N'MS-0562', N'Line Full', @MachAsm, NULL, 1),
(N'MS-0563', N'Gauging Parts', @MachAsm, NULL, 1),
(N'MS-0564', N'Transfer', @MachAsm, NULL, 1),
(N'MS-0565', N'OP10 Down', @MachAsm, NULL, 0),
(N'MS-0567', N'OP10-1 Down', @MachAsm, NULL, 0),
(N'MS-0568', N'OP10-2 Down', @MachAsm, NULL, 0),
(N'MS-0569', N'OP10-3 Down', @MachAsm, NULL, 0),
(N'MS-0570', N'OP10-4 Down', @MachAsm, NULL, 0),
(N'MS-0571', N'OP10-5 Down', @MachAsm, NULL, 0),
(N'MS-0572', N'OP10-6 Down', @MachAsm, NULL, 0),
(N'MS-0573', N'OP10-7 Down', @MachAsm, NULL, 0),
(N'MS-0574', N'OP20 Down', @MachAsm, NULL, 0),
(N'MS-0575', N'OP20-1 Down', @MachAsm, NULL, 0),
(N'MS-0576', N'OP20-2 Down', @MachAsm, NULL, 0),
(N'MS-0577', N'OP20-3 Down', @MachAsm, NULL, 0),
(N'MS-0578', N'OP20/30 Down', @MachAsm, NULL, 0),
(N'MS-0579', N'OP20/30-1 Down', @MachAsm, NULL, 0),
(N'MS-0580', N'OP20/30-2 Down', @MachAsm, NULL, 0),
(N'MS-0581', N'OP30 Down', @MachAsm, NULL, 0),
(N'MS-0582', N'OP30-1 Down', @MachAsm, NULL, 0),
(N'MS-0583', N'OP30-2 Down', @MachAsm, NULL, 0),
(N'MS-0584', N'OP30-3 Down', @MachAsm, NULL, 0),
(N'MS-0585', N'Deburr Down', @MachAsm, NULL, 0),
(N'MS-0586', N'FEC Down', @MachAsm, NULL, 0),
(N'MS-0587', N'Face Height Down', @MachAsm, NULL, 0),
(N'MS-0588', N'OP60 Down', @MachAsm, NULL, 0),
(N'MS-0589', N'OP70-1 Down', @MachAsm, NULL, 0),
(N'MS-0590', N'OP70-2 Down', @MachAsm, NULL, 0),
(N'MS-0591', N'OP70-A Down', @MachAsm, NULL, 0),
(N'MS-0592', N'OP70-B Down', @MachAsm, NULL, 0),
(N'MS-0593', N'Shut down due to weather', @MachAsm, NULL, 1),
(N'MS-0594', N'Rework', @MachAsm, NULL, 0),
(N'MS-0595', N'C-Clip Insert', @MachAsm, NULL, 0),
(N'MS-0596', N'Lost Motion', @MachAsm, NULL, 0),
(N'MS-0597', N'Dowel Pin Feed Machine', @MachAsm, NULL, 0),
(N'MS-0598', N'VCM Ex "A"', @MachAsm, NULL, 0),
(N'MS-0599', N'VCM Ex "B"', @MachAsm, NULL, 0),
(N'MS-0600', N'VCM "IN"', @MachAsm, NULL, 0),
(N'MS-0601', N'VCM "IN" R/A', @MachAsm, NULL, 0),
(N'MS-0602', N'Non VCM "IN"', @MachAsm, NULL, 0),
(N'MS-0603', N'Non VCM "A" R/A', @MachAsm, NULL, 0),
(N'MS-0604', N'Non VCM "B" R/A', @MachAsm, NULL, 0),
(N'MS-0605', N'Non VCM Ex "A"', @MachAsm, NULL, 0),
(N'MS-0606', N'Non VCM Ex "B"', @MachAsm, NULL, 0),
(N'MS-0607', N'IN R/S Front', @MachAsm, NULL, 0),
(N'MS-0608', N'IN R/S Rear', @MachAsm, NULL, 0),
(N'MS-0609', N'IN R/S RKG', @MachAsm, NULL, 0),
(N'MS-0610', N'IN Shafts', @MachAsm, NULL, 0),
(N'MS-0611', N'Ex Shafts', @MachAsm, NULL, 0),
(N'MS-0612', N'EX R/S Front', @MachAsm, NULL, 0),
(N'MS-0613', N'EX R/S Rear', @MachAsm, NULL, 0),
(N'MS-0614', N'EX R/S RKG', @MachAsm, NULL, 0),
(N'MS-0615', N'Mounting Bolt Feed Machine', @MachAsm, NULL, 0),
(N'MS-0616', N'Bolt Torque Machine', @MachAsm, NULL, 0),
(N'MS-0617', N'Inspection Unit', @MachAsm, NULL, 0),
(N'MS-0618', N'#1/#3 OP10/20-1', @MachAsm, NULL, 0),
(N'MS-0619', N'#1/#3 OP10/20-2', @MachAsm, NULL, 0),
(N'MS-0620', N'#2 OP10/20-1', @MachAsm, NULL, 0),
(N'MS-0621', N'#2 OP10/20-2', @MachAsm, NULL, 0),
(N'MS-0622', N'OP21', @MachAsm, NULL, 0),
(N'MS-0623', N'OP22', @MachAsm, NULL, 0),
(N'MS-0624', N'OP40-1', @MachAsm, NULL, 0),
(N'MS-0625', N'OP40-2', @MachAsm, NULL, 0),
(N'MS-0626', N'OP40-3', @MachAsm, NULL, 0),
(N'MS-0627', N'OP40-4', @MachAsm, NULL, 0),
(N'MS-0628', N'QA Machine', @MachAsm, NULL, 0),
(N'MS-0629', N'Label Maker', @MachAsm, NULL, 0),
(N'MS-0630', N'Robot', @MachAsm, NULL, 0),
(N'MS-0631', N'Warm Up Machines', @MachAsm, NULL, 1),
(N'MS-0632', N'No Operator due to Absence', @MachAsm, NULL, 1),
(N'MS-0633', N'No Operator due to Sorting In-House', @MachAsm, NULL, 1),
(N'MS-0634', N'No Parts to Inspect', @MachAsm, NULL, 0),
(N'MS-0635', N'Misset Problems', @MachAsm, NULL, 0),
(N'MS-0636', N'CMM Confirmation of Change Point', @MachAsm, NULL, 0),
(N'MS-0637', N'CMM Confirmation of Changeover', @MachAsm, NULL, 0),
(N'MS-0638', N'Transfer (VCM)', @MachAsm, NULL, 0),
(N'MS-0639', N'RKR Arm Load', @MachAsm, NULL, 0),
(N'MS-0640', N'RKR Holder Load', @MachAsm, NULL, 0),
(N'MS-0641', N'Shaft Install', @MachAsm, NULL, 0),
(N'MS-0642', N'Laser Engraver', @MachAsm, NULL, 0),
(N'MS-0643', N'Flexware', @MachAsm, NULL, 0),
(N'MS-0644', N'Waiting on Maintenance', @MachAsm, NULL, 0),
(N'MS-0645', N'OP 10/20-1 #1/#3', @MachAsm, NULL, 0),
(N'MS-0646', N'OP 10/20-1 #2', @MachAsm, NULL, 0),
(N'MS-0647', N'OP 10/20-2 #1/#3', @MachAsm, NULL, 0),
(N'MS-0648', N'OP 10/20-2 #2', @MachAsm, NULL, 0),
(N'MS-0649', N'OP10/20-3 #1/#3', @MachAsm, NULL, 0),
(N'MS-0650', N'OP10/20-3 #2', @MachAsm, NULL, 0),
(N'MS-0651', N'Scheduled Downtime', @MachAsm, NULL, 0),
(N'MS-0652', N'Washer Awareness', @MachAsm, NULL, 0),
(N'MS-0653', N'Washer Cutout', @MachAsm, NULL, 0),
(N'MS-0654', N'Robot Line #1 (Walle)', @MachAsm, NULL, 0),
(N'MS-0655', N'Robot Line #2 (Geisha)', @MachAsm, NULL, 0),
(N'MS-0656', N'Robot Line #3 (Gizmo)', @MachAsm, NULL, 0),
(N'MS-0657', N'No Die Cast Parts', @MachAsm, NULL, 0),
(N'MS-0658', N'MS Quality Issues', @MachAsm, NULL, 0),
(N'MS-0659', N'DC Quality Issues', @MachAsm, NULL, 0),
(N'MS-0660', N'Waiting on Part for Machine', @MachAsm, NULL, 0),
(N'MS-0661', N'No Dunnage', @MachAsm, NULL, 0),
(N'MS-0662', N'OP50 Down', @MachAsm, NULL, 0)
;

INSERT INTO Oee.DowntimeReasonCode
    (Code, Description, OperationCategoryId, DowntimeReasonTypeId, IsExcused, CreatedByUserId)
SELECT c.Code, c.Description, c.OperationCategoryId,
       (SELECT t.Id FROM Oee.DowntimeReasonType t WHERE t.Id = c.DowntimeReasonTypeId),
       c.IsExcused, @Usr
FROM @Codes c
WHERE NOT EXISTS (SELECT 1 FROM Oee.DowntimeReasonCode d WHERE d.Code = c.Code);

PRINT 'Seed 031 (FRS downtime reason codes) applied: ' + CAST(@@ROWCOUNT AS NVARCHAR(10)) + ' new rows.';
GO
